apiVersion: tower.ansible.com/v1beta1
kind: Tower
metadata:
  name: awx
  namespace: default
spec:
  tower_hostname: 127.0.0.1.xip.io
  tower_secret_key: aabbcc
 
  tower_admin_user: admin
  tower_admin_email: admin@example.net
  tower_admin_password: password

  deployment_type: awx
  tower_ingress_type: ingress

  tower_task_image: ansible/awx_task:11.2.0
  tower_web_image: ansible/awx_web:11.2.0

  tower_postgres_storage_class: ''

  tower_task_mem_request: 2Gi
  tower_task_cpu_request: 3000m

  tower_create_preload_data: true

  tower_create_container_group: true
  tower_container_group_image: sgryczan/ansible-runner:0.0.0

  tower_hpa_enabled: true
  hpa_min_replicas: 2
  hpa_max_replicas: 5
  hpa_target_cpu_util_percent: 80

  ldap_enabled: false
  allow_anonymous_bind: true
  ldap_server_uri: "ldap://<LDAP SERVER>:389"
  ldap_user_search: "ou=People,dc=ds,dc=eng,dc=org,dc=com"
  ldap_group_search_dn: "ou=Managed,ou=Groups,dc=ds,dc=eng,dc=org,dc=com"
  ldap_superuser_group: "CN=awx-admins,ou=Managed,ou=Groups,dc=ds,dc=eng,dc=org,dc=com"
  ldap_organizations:
    Team1:
      admins: "CN=team1,ou=Managed,ou=Groups,dc=ds,dc=eng,dc=org,dc=com"
      remove_admins: false
