FROM ansible/awx_task:9.3.0

USER root
COPY 9.2.0-patches/awx/main/dispatch/periodic.py /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/
COPY 9.2.0-patches/awx/main/management/commands/run_dispatcher.py /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/